name: insert-hooks-and-build-d8

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  insert-and-build:
    runs-on: self-hosted
    timeout-minutes: 0

    env:
      BQRS_DIR: "/home/user/app/bqrs"
      HOOK_TOOL_DIR: "/home/user/app/hook_tool"
      INSERT_HOOK: "/home/user/app/hook_tool/insert_hook.py"
      V8SRC: "/home/user/app"
      REMAP: "/app/v8=/home/user/app"
      V8BUILD: "/home/user/app"
      CODEQL: "/home/user/codeql-cli/codeql/codeql"
      CODEQL_ALLOW_INSTALLATION_ANYWHERE: "true"

    steps:
      - name: Show context
        shell: bash
        run: |
          whoami
          python3 --version || true
          echo "BQRS_DIR=$BQRS_DIR"
          echo "HOOK_TOOL_DIR=$HOOK_TOOL_DIR"
          echo "V8SRC=$V8SRC"
          echo "V8BUILD=$V8BUILD"
          echo "CODEQL=$CODEQL"

      - name: Sanity check directories
        shell: bash
        run: |
          test -d "$BQRS_DIR"       || { echo "::error::No BQRS_DIR at $BQRS_DIR"; exit 1; }
          test -d "$HOOK_TOOL_DIR"  || { echo "::error::No HOOK_TOOL_DIR at $HOOK_TOOL_DIR"; exit 1; }
          test -f "$INSERT_HOOK"    || { echo "::error::insert_hook.py not found at $INSERT_HOOK"; exit 1; }
          test -d "$V8SRC/v8"       || { echo "::error::Expected $V8SRC/v8 to exist"; exit 1; }
          test -f "$V8SRC/v8/BUILD.gn" || { echo "::error::Expected $V8SRC/v8/BUILD.gn"; exit 1; }

      - name: Copy hooks into v8/tools
        shell: bash
        run: |
          set -euo pipefail
          src="$HOOK_TOOL_DIR/hooks"
          dst="$V8SRC/v8/tools/hooks"
          test -d "$src" || { echo "::error::hooks dir not found at $src"; exit 1; }
          mkdir -p "$dst"
          rsync -rltD --omit-dir-times --no-owner --no-group --no-perms "$src"/ "$dst"/

      - name: Patch BUILD.gn via script
        shell: bash
        run: |
          python3 "$HOOK_TOOL_DIR/patch_build_gn.py" "$V8SRC/v8"

      - name: Run insert_hook.py for all BQRS
        shell: bash
        working-directory: /home/user/app
        run: |
          shopt -s globstar nullglob
          cnt=0
          for b in "$BQRS_DIR"/**/*.bqrs; do
            rel="${b#"$BQRS_DIR"/}"
            echo "[hook] $rel"
            python3 "$INSERT_HOOK" "$b" --codeql "$CODEQL" --root "$V8SRC" --remap "$REMAP"
            cnt=$((cnt+1))
          done
          echo "Total processed: $cnt"
          if [ $cnt -eq 0 ]; then
            echo "::warning::No .bqrs files found under $BQRS_DIR"
          fi

      - name: Build d8 with ninja (out.gn/x64.debug)
        shell: bash
        working-directory: /home/user/app/v8
        run: |
          J=$(( $(nproc) / 2 )); [ $J -ge 2 ] || J=2
          echo "Using -j$J -l$J"
          ninja -C out.gn/x64.debug d8 -j"$J" -l"$J"
