name: Sync Fork with Upstream

on:
  # schedule:
  #   - cron: '0 */6 * * *'   # 매 6시간마다 정각 (UTC 기준)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Sync with Upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/v8/v8.git || true
          git fetch upstream
          git checkout main
          git merge --ff-only upstream/main || git merge --no-edit upstream/main
          git push origin main
